# 07_assemble_steering_grids.py
"""Assemble steering grids from images generated by 06_find_best_demos.py"""

import os
import json
from PIL import Image, ImageDraw

from config import get_config
from io_utils import write_json, ensure_dir


def assemble_grid_from_existing(
    demos_dir: str,
    feature_id: int,
    image_id: int,
    strengths: list,
    img_width: int,
    img_height: int,
) -> Image.Image:
    """Assemble grid from pre-generated images."""
    
    feat_dir = os.path.join(demos_dir, f"feature_{feature_id}")
    
    images = []
    
    for strength in strengths:
        if strength == 0:
            img_path = os.path.join(feat_dir, f"{image_id:06d}_baseline.png")
        elif strength > 0:
            img_path = os.path.join(feat_dir, f"{image_id:06d}_pos_{abs(strength):.0f}.png")
        else:
            img_path = os.path.join(feat_dir, f"{image_id:06d}_neg_{abs(strength):.0f}.png")
        
        if not os.path.exists(img_path):
            raise FileNotFoundError(f"Missing image: {img_path}")
        
        img = Image.open(img_path)
        images.append((strength, img))
    
    # Create grid
    n = len(images)
    label_height = 40
    grid = Image.new('RGB', (img_width * n, img_height + label_height), (255, 255, 255))
    draw = ImageDraw.Draw(grid)
    
    for i, (strength, img) in enumerate(images):
        grid.paste(img, (i * img_width, label_height))
        
        label_text = f"{strength:+.0f}" if strength != 0 else "baseline"
        bbox = draw.textbbox((0, 0), label_text)
        text_width = bbox[2] - bbox[0]
        x = i * img_width + (img_width - text_width) // 2
        draw.text((x, 10), label_text, fill=(0, 0, 0))
    
    return grid


def main():
    cfg = get_config()
    
    best_demos_path = os.path.join(cfg.out_dir, "best_demos", "best_demo_candidates.json")
    demos_dir = os.path.join(cfg.out_dir, "best_demos")
    output_dir = os.path.join(cfg.out_dir, "steering_grids")
    
    if not os.path.exists(best_demos_path):
        raise FileNotFoundError(f"Run 06_find_best_demos.py first: {best_demos_path}")
    
    with open(best_demos_path, "r") as f:
        best_demos_data = json.load(f)
    
    ensure_dir(output_dir)
    
    # Build strengths from config (symmetric around 0)
    test_strengths = best_demos_data["config"]["test_strengths"]
    strengths = sorted([-s for s in test_strengths] + [0] + test_strengths)
    
    print(f"Assembling grids with strengths: {strengths}")
    
    summary = {
        "strengths": strengths,
        "grids": [],
    }
    
    for feat_data in best_demos_data["features"]:
        feature_id = feat_data["feature_id"]
        
        feat_output_dir = os.path.join(output_dir, f"feature_{feature_id}")
        ensure_dir(feat_output_dir)
        
        for demo_idx, demo in enumerate(feat_data["best_demos"]):
            image_id = demo["image_id"]
            prompt = demo["prompt"]
            seed = demo["seed"]
            score = demo.get("combined_score", 0)
            
            print(f"Feature {feature_id}, demo {demo_idx} (image {image_id})...")
            
            try:
                grid = assemble_grid_from_existing(
                    demos_dir=demos_dir,
                    feature_id=feature_id,
                    image_id=image_id,
                    strengths=strengths,
                    img_width=cfg.width,
                    img_height=cfg.height,
                )
                
                # Save to feature folder
                grid_filename = f"feature_{feature_id}_demo_{demo_idx}_img_{image_id}.png"
                grid_path = os.path.join(feat_output_dir, grid_filename)
                grid.save(grid_path)
                
                # Also save flat copy for easy browsing
                flat_filename = f"grid_f{feature_id}_d{demo_idx}.png"
                flat_path = os.path.join(output_dir, flat_filename)
                grid.save(flat_path)
                
                summary["grids"].append({
                    "feature_id": feature_id,
                    "demo_idx": demo_idx,
                    "image_id": image_id,
                    "prompt": prompt,
                    "seed": seed,
                    "score": score,
                    "grid_path": os.path.relpath(grid_path, cfg.out_dir),
                })
                
                print(f"  Saved: {flat_filename}")
                
            except FileNotFoundError as e:
                print(f"  Skipping: {e}")
    
    summary_path = os.path.join(output_dir, "steering_grids_summary.json")
    write_json(summary_path, summary)
    
    print(f"\nDone! {len(summary['grids'])} grids saved to {output_dir}")


if __name__ == "__main__":
    main()